### ISSUE TITLE
episode_related no such element

### ISSUE THREAD

**Issue by amenome** [pseudonomynous/animeDownloader#14]
Just started happening this morning - not sure if they changed their site, or if this is some other problem.

```
Traceback (most recent call last):
  File "./anime.py", line 225, in <module>
    updateAnime()
  File "./anime.py", line 120, in updateAnime
    download(link, title, season, loc, subOrDub)
  File "./anime.py", line 151, in download
    epList = driver.find_element_by_xpath("//ul[contains(@id, 'episode_related')]")
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@id, 'episode_related')]"}
  (Session info: headless chrome=88.0.4324.150)
```

**Comment by amenome** [comment]
Looks like maybe a speed issue on a page that has lots and lots of episodes.

**Comment by amenome** [comment]
Testing adding a sleep function.

**Comment by pseudonomynous** [comment]
This happened for me after Shield Hero, on Steins Gate. I moved that to the front of myAnime.txt, and that seems to work. Also, I've updated all my links to gogoanime.sh instead of gogoanime.so. Not sure that makes a difference, but now it works for me when I update them.

**Comment by pseudonomynous** [comment]
Seems to be inconsistent. Just ran after that change, no error. Ran again, didn't actually run. Ran once more, error on Afro Samurai.

**Comment by pseudonomynous** [comment]
Not sure if it's episode count; all my anime have 12 episodes, only one has 60+.

**Comment by pseudonomynous** [comment]
Some of them have episode_related not episode-related. Hrm....

**Comment by amenome** [comment]
Added sleep function in pull request.
